Ví dụ 4.5.1.1


In [8]:
import pandas as pd
import numpy as np

In [9]:
rng = np.random.RandomState(100)  #tạo mảng Numpy ngẫu nhiên Cố Định
arr1=rng.randint(0,10,4)
arr2=rng.randint(0,10,(3,4))
print('arr1:',arr1)
print('\n arr2:\n',arr2)

arr1: [8 8 3 7]

 arr2:
 [[7 0 4 2]
 [5 2 2 2]
 [1 0 8 4]]


In [10]:
sr = pd.Series(arr1)
df=pd.DataFrame(arr2,columns=['A','B','C','D'])
print("Series:\n",sr)
print("DataFrame:\n",df)

Series:
 0    8
1    8
2    3
3    7
dtype: int32
DataFrame:
    A  B  C  D
0  7  0  4  2
1  5  2  2  2
2  1  0  8  4


In [11]:
np.exp(sr)

0    2980.957987
1    2980.957987
2      20.085537
3    1096.633158
dtype: float64

In [12]:
np.sin(df*np.pi/4)

A    B             C             D
0 -0.707107  0.0  1.224647e-16  1.000000e+00
1 -0.707107  1.0  1.000000e+00  1.000000e+00
2  0.707107  0.0 -2.449294e-16  1.224647e-16

Ví dụ 4.5.1.3


In [ ]:
# tạo 2 series A,B và tính tổng các giá trị
A=pd.Series([1,3,5],index=[0,1,2])
B=pd.Series([2,4,5],index=[1,2,3])

